### ISSUE TITLE
What's next? 

### ISSUE THREAD

**Issue by maciekgrzybek** [opensource-matrix/snippet#3]
Hey, just wanted to say that this is very interesting idea for a package :) my question is, what's next? I'd more than happy to contribute with JS snippets, but not sure what kind of snippets you're looking for :)

**Comment by marc2332** [comment]
Same opinion of @maciekgrzybek . A deeper explanation would be great. Looks interesting 😄

**Comment by RevelMind** [comment]
Hi, Thanks for your opinions! :)

I am really just looking for examples such as how to use a function from a certain library, etc.  They can be short or long snippets of code, I suggest looking at some GH gists for ideas/inspiration or just entire snippets.

> This issue will be closed in 48 hours if there are no further replies.

**Comment by astronomizedev** [comment]
@RevelMind share this with everybody else not just the poeple who asked .-.
